//AUTOGENERATED ON Tue Mar 12 19:20:36 2024 - DO NOT EDIT!

/*
Data for Pinviewer for external Board for Colorlight i9 v7.2
ALPHA VERSION! - INCOMPLETE! - Feedback welcome

(c) 2024 by kittennbfive - CC BY-NC-SA 4.0
https://github.com/kittennbfive
*/

const connectors=new Map(
[
	['1', new Map([
		['orientation', 'vert'],
		['pos_pin1', 'top_left'],
		['1', new Map([
			['type', 'ETHERNET'],
			['connected_to', 'ETH: ETH1_2_P'],
			['is_diff_pair', 'false']
		])],
		['2', new Map([
			['type', 'ETHERNET'],
			['connected_to', 'ETH: ETH1_2_N'],
			['is_diff_pair', 'false']
		])],
		['3', new Map([
			['type', 'ETHERNET'],
			['connected_to', 'ETH: ETH1_1_N'],
			['is_diff_pair', 'false']
		])],
		['4', new Map([
			['type', 'ETHERNET'],
			['connected_to', 'ETH: ETH_1_1_P'],
			['is_diff_pair', 'false']
		])],
		['5', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['6', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])],
		['7', new Map([
			['type', 'FIXED_NC'],
			['connected_to', '(NC)'],
			['is_diff_pair', 'false']
		])],
		['8', new Map([
			['type', 'FIXED_5V'],
			['connected_to', '5V'],
			['is_diff_pair', 'false']
		])],
		['9', new Map([
			['type', 'FIXED_NC'],
			['connected_to', '(NC)'],
			['is_diff_pair', 'false']
		])],
		['10', new Map([
			['type', 'ETHERNET'],
			['connected_to', 'ETH: ETH2_1_P'],
			['is_diff_pair', 'false']
		])],
		['11', new Map([
			['type', 'ETHERNET'],
			['connected_to', 'ETH: ETH2_1_N'],
			['is_diff_pair', 'false']
		])],
		['12', new Map([
			['type', 'ETHERNET'],
			['connected_to', 'ETH: ETH2_2_N'],
			['is_diff_pair', 'false']
		])],
		['13', new Map([
			['type', 'ETHERNET'],
			['connected_to', 'ETH: ETH2_2_P'],
			['is_diff_pair', 'false']
		])],
		['14', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['15', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])],
		['16', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])],
		['17', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['18', new Map([
			['type', 'ETHERNET'],
			['connected_to', 'ETH: ETH2_4_P'],
			['is_diff_pair', 'false']
		])],
		['19', new Map([
			['type', 'ETHERNET'],
			['connected_to', 'ETH: ETH2_4_N'],
			['is_diff_pair', 'false']
		])],
		['20', new Map([
			['type', 'ETHERNET'],
			['connected_to', 'ETH: ETH2_3_N'],
			['is_diff_pair', 'false']
		])],
		['21', new Map([
			['type', 'ETHERNET'],
			['connected_to', 'ETH: ETH2_3_P'],
			['is_diff_pair', 'false']
		])],
		['22', new Map([
			['type', 'FIXED_NC'],
			['connected_to', '(NC)'],
			['is_diff_pair', 'false']
		])],
		['23', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['24', new Map([
			['type', 'FIXED_NC'],
			['connected_to', '(NC)'],
			['is_diff_pair', 'false']
		])],
		['25', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])],
		['26', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['27', new Map([
			['type', 'ETHERNET'],
			['connected_to', 'ETH: ETH1_3_P'],
			['is_diff_pair', 'false']
		])],
		['28', new Map([
			['type', 'ETHERNET'],
			['connected_to', 'ETH: ETH1_3_N'],
			['is_diff_pair', 'false']
		])],
		['29', new Map([
			['type', 'ETHERNET'],
			['connected_to', 'ETH: ETH1_4_N'],
			['is_diff_pair', 'false']
		])],
		['30', new Map([
			['type', 'ETHERNET'],
			['connected_to', 'ETH: ETH1_4_P'],
			['is_diff_pair', 'false']
		])]
	])],
	['2', new Map([
		['orientation', 'horiz'],
		['pos_pin1', 'top_right'],
		['1', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])],
		['2', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['3', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: K18'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'J18'], ['connector_complement', '6'], ['pin_complement', '3'] ])]
		])],
		['4', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: T18'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'U19'], ['connector_complement', 'NC'], ['pin_complement', 'NC'] ])]
		])],
		['5', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: R17'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'R16'], ['connector_complement', 'NC'], ['pin_complement', 'NC'] ])]
		])],
		['6', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: M17'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'N16'], ['connector_complement', 'NC'], ['pin_complement', 'NC'] ])]
		])],
		['7', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: U18'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'U17'], ['connector_complement', '2'], ['pin_complement', '22'] ])]
		])],
		['8', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['9', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: P18'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'P19'], ['connector_complement', 'NC'], ['pin_complement', 'NC'] ])]
		])],
		['10', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])],
		['11', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['12', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: N18'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'P17'], ['connector_complement', '2'], ['pin_complement', '25'] ])]
		])],
		['13', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: L20'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'M20'], ['connector_complement', 'NC'], ['pin_complement', 'NC'] ])]
		])],
		['14', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: K20'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'J20'], ['connector_complement', '2'], ['pin_complement', '16'] ])]
		])],
		['15', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: G20'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'F20'], ['connector_complement', '3'], ['pin_complement', '28'] ])]
		])],
		['16', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: J20'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'K20'], ['connector_complement', '2'], ['pin_complement', '14'] ])]
		])],
		['17', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: L18'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'M18'], ['connector_complement', '2'], ['pin_complement', '18'] ])]
		])],
		['18', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: M18'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'L18'], ['connector_complement', '2'], ['pin_complement', '17'] ])]
		])],
		['19', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: N17'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'P16'], ['connector_complement', '6'], ['pin_complement', '4'] ])]
		])],
		['20', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['21', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])],
		['22', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: U17'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'U18'], ['connector_complement', '2'], ['pin_complement', '7'] ])]
		])],
		['23', new Map([
			['type', 'FIXED_5V'],
			['connected_to', '5V'],
			['is_diff_pair', 'false']
		])],
		['24', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: T17'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'U16'], ['connector_complement', 'NC'], ['pin_complement', 'NC'] ])]
		])],
		['25', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: P17'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'N18'], ['connector_complement', '2'], ['pin_complement', '12'] ])]
		])],
		['26', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: R18'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'T19'], ['connector_complement', 'NC'], ['pin_complement', 'NC'] ])]
		])],
		['27', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: C18'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'D17'], ['connector_complement', '5'], ['pin_complement', '6'] ])]
		])],
		['28', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: L2'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'L3'], ['connector_complement', 'NC'], ['pin_complement', 'NC'] ])]
		])],
		['29', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['30', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])]
	])],
	['3', new Map([
		['orientation', 'horiz'],
		['pos_pin1', 'top_right'],
		['1', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])],
		['2', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['3', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: D20'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'E19'], ['connector_complement', '4'], ['pin_complement', '17'] ])]
		])],
		['4', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: B19'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'A18'], ['connector_complement', '3'], ['pin_complement', '6'] ])]
		])],
		['5', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: A19'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'B20'], ['connector_complement', '3'], ['pin_complement', '27'] ])]
		])],
		['6', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: A18'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'B19'], ['connector_complement', '3'], ['pin_complement', '4'] ])]
		])],
		['7', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: C4'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'B4'], ['connector_complement', '3'], ['pin_complement', '22'] ])]
		])],
		['8', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['9', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: C3'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'D3'], ['connector_complement', '3'], ['pin_complement', '24'] ])]
		])],
		['10', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])],
		['11', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['12', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: A3'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'B3'], ['connector_complement', '4'], ['pin_complement', '18'] ])]
		])],
		['13', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: B1'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'A2'], ['connector_complement', '4'], ['pin_complement', '12'] ])]
		])],
		['14', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: D2'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'E1'], ['connector_complement', '4'], ['pin_complement', '3'] ])]
		])],
		['15', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: E2'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'F2'], ['connector_complement', '4'], ['pin_complement', '28'] ])]
		])],
		['16', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: D1'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'C1'], ['connector_complement', '3'], ['pin_complement', '17'] ])]
		])],
		['17', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: C1'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'D1'], ['connector_complement', '3'], ['pin_complement', '16'] ])]
		])],
		['18', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: C2'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'B2'], ['connector_complement', '4'], ['pin_complement', '14'] ])]
		])],
		['19', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: E3'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'F4'], ['connector_complement', '5'], ['pin_complement', '3'] ])]
		])],
		['20', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['21', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])],
		['22', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: B4'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'C4'], ['connector_complement', '3'], ['pin_complement', '7'] ])]
		])],
		['23', new Map([
			['type', 'FIXED_5V'],
			['connected_to', '5V'],
			['is_diff_pair', 'false']
		])],
		['24', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: D3'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'C3'], ['connector_complement', '3'], ['pin_complement', '9'] ])]
		])],
		['25', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: C17'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'B17'], ['connector_complement', 'NC'], ['pin_complement', 'NC'] ])]
		])],
		['26', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: B18'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'A17'], ['connector_complement', 'NC'], ['pin_complement', 'NC'] ])]
		])],
		['27', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: B20'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'A19'], ['connector_complement', '3'], ['pin_complement', '5'] ])]
		])],
		['28', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: F20'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'G20'], ['connector_complement', '2'], ['pin_complement', '15'] ])]
		])],
		['29', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['30', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])]
	])],
	['4', new Map([
		['orientation', 'vert'],
		['pos_pin1', 'top_left'],
		['1', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])],
		['2', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['3', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: E1'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'D2'], ['connector_complement', '3'], ['pin_complement', '14'] ])]
		])],
		['4', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: E4'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'D5'], ['connector_complement', 'NC'], ['pin_complement', 'NC'] ])]
		])],
		['5', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: F3'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'G3'], ['connector_complement', '4'], ['pin_complement', '26'] ])]
		])],
		['6', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: H3'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'H5'], ['connector_complement', '4'], ['pin_complement', '7'] ])]
		])],
		['7', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: H5'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'H3'], ['connector_complement', '4'], ['pin_complement', '6'] ])]
		])],
		['8', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['9', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: J5'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'J4'], ['connector_complement', '4'], ['pin_complement', '24'] ])]
		])],
		['10', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])],
		['11', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['12', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: A2'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'B1'], ['connector_complement', '3'], ['pin_complement', '13'] ])]
		])],
		['13', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: K4'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'K5'], ['connector_complement', '4'], ['pin_complement', '19'] ])]
		])],
		['14', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: B2'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'C2'], ['connector_complement', '3'], ['pin_complement', '18'] ])]
		])],
		['15', new Map([
			['type', 'FIXED_NC'],
			['connected_to', '(NC)'],
			['is_diff_pair', 'false']
		])],
		['16', new Map([
			['type', 'FIXED_NC'],
			['connected_to', '(NC)'],
			['is_diff_pair', 'false']
		])],
		['17', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: E19'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'D20'], ['connector_complement', '3'], ['pin_complement', '3'] ])]
		])],
		['18', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: B3'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'A3'], ['connector_complement', '3'], ['pin_complement', '12'] ])]
		])],
		['19', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: K5'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'K4'], ['connector_complement', '4'], ['pin_complement', '13'] ])]
		])],
		['20', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['21', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])],
		['22', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: K3'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'J3'], ['connector_complement', 'NC'], ['pin_complement', 'NC'] ])]
		])],
		['23', new Map([
			['type', 'FIXED_5V'],
			['connected_to', '5V'],
			['is_diff_pair', 'false']
		])],
		['24', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: J4'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'J5'], ['connector_complement', '4'], ['pin_complement', '9'] ])]
		])],
		['25', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: H4'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'G5'], ['connector_complement', '5'], ['pin_complement', '26'] ])]
		])],
		['26', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: G3'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'F3'], ['connector_complement', '4'], ['pin_complement', '5'] ])]
		])],
		['27', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: F1'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'G2'], ['connector_complement', 'NC'], ['pin_complement', 'NC'] ])]
		])],
		['28', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: F2'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'E2'], ['connector_complement', '3'], ['pin_complement', '15'] ])]
		])],
		['29', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['30', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])]
	])],
	['5', new Map([
		['orientation', 'horiz'],
		['pos_pin1', 'bottom_left'],
		['1', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])],
		['2', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['3', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: F4'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'E3'], ['connector_complement', '3'], ['pin_complement', '19'] ])]
		])],
		['4', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: E6'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'D6'], ['connector_complement', 'NC'], ['pin_complement', 'NC'] ])]
		])],
		['5', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: D16'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'C16'], ['connector_complement', 'NC'], ['pin_complement', 'NC'] ])]
		])],
		['6', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: D17'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'C18'], ['connector_complement', '2'], ['pin_complement', '27'] ])]
		])],
		['7', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: E17'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'D18'], ['connector_complement', '5'], ['pin_complement', '25'] ])]
		])],
		['8', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['9', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: F16'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'E16'], ['connector_complement', '5'], ['pin_complement', '24'] ])]
		])],
		['10', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])],
		['11', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['12', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: E18'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'F18'], ['connector_complement', '5'], ['pin_complement', '13'] ])]
		])],
		['13', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: F18'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'E18'], ['connector_complement', '5'], ['pin_complement', '12'] ])]
		])],
		['14', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: G18'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'F17'], ['connector_complement', '5'], ['pin_complement', '22'] ])]
		])],
		['15', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: H18'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'H17'], ['connector_complement', '5'], ['pin_complement', '17'] ])]
		])],
		['16', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: J17'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'J16'], ['connector_complement', '6'], ['pin_complement', '28'] ])]
		])],
		['17', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: H17'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'H18'], ['connector_complement', '5'], ['pin_complement', '15'] ])]
		])],
		['18', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: H16'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'G16'], ['connector_complement', '5'], ['pin_complement', '19'] ])]
		])],
		['19', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: G16'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'H16'], ['connector_complement', '5'], ['pin_complement', '18'] ])]
		])],
		['20', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['21', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])],
		['22', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: F17'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'G18'], ['connector_complement', '5'], ['pin_complement', '14'] ])]
		])],
		['23', new Map([
			['type', 'FIXED_5V'],
			['connected_to', '5V'],
			['is_diff_pair', 'false']
		])],
		['24', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: E16'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'F16'], ['connector_complement', '5'], ['pin_complement', '9'] ])]
		])],
		['25', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: D18'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'E17'], ['connector_complement', '5'], ['pin_complement', '7'] ])]
		])],
		['26', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: G5'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'H4'], ['connector_complement', '4'], ['pin_complement', '25'] ])]
		])],
		['27', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: F5'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'E5'], ['connector_complement', '5'], ['pin_complement', '28'] ])]
		])],
		['28', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: E5'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'F5'], ['connector_complement', '5'], ['pin_complement', '27'] ])]
		])],
		['29', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['30', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])]
	])],
	['6', new Map([
		['orientation', 'horiz'],
		['pos_pin1', 'bottom_left'],
		['1', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])],
		['2', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['3', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: J18'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'K18'], ['connector_complement', '2'], ['pin_complement', '3'] ])]
		])],
		['4', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: P16'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'N17'], ['connector_complement', '2'], ['pin_complement', '19'] ])]
		])],
		['5', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: L4'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'L5'], ['connector_complement', '6'], ['pin_complement', '27'] ])]
		])],
		['6', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: N4'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'P5'], ['connector_complement', 'NC'], ['pin_complement', 'NC'] ])]
		])],
		['7', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: T3'],
			['is_diff_pair', 'false']
		])],
		['8', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['9', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: T2'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'U2'], ['connector_complement', 'NC'], ['pin_complement', 'NC'] ])]
		])],
		['10', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])],
		['11', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['12', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: N2'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'M1'], ['connector_complement', '6'], ['pin_complement', '19'] ])]
		])],
		['13', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: V1'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'U1'], ['connector_complement', '6'], ['pin_complement', '17'] ])]
		])],
		['14', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: Y2'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'W1'], ['connector_complement', '6'], ['pin_complement', '18'] ])]
		])],
		['15', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: T1'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'R1'], ['connector_complement', '6'], ['pin_complement', '16'] ])]
		])],
		['16', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: R1'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'T1'], ['connector_complement', '6'], ['pin_complement', '15'] ])]
		])],
		['17', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: U1'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'V1'], ['connector_complement', '6'], ['pin_complement', '13'] ])]
		])],
		['18', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: W1'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'Y2'], ['connector_complement', '6'], ['pin_complement', '14'] ])]
		])],
		['19', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: M1'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'N2'], ['connector_complement', '6'], ['pin_complement', '12'] ])]
		])],
		['20', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['21', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])],
		['22', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: N3'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'M3'], ['connector_complement', '6'], ['pin_complement', '24'] ])]
		])],
		['23', new Map([
			['type', 'FIXED_5V'],
			['connected_to', '5V'],
			['is_diff_pair', 'false']
		])],
		['24', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: M3'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'N3'], ['connector_complement', '6'], ['pin_complement', '22'] ])]
		])],
		['25', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: R3'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'R2'], ['connector_complement', 'NC'], ['pin_complement', 'NC'] ])]
		])],
		['26', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: M4'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_TRUE'], ['pin_fpga_complement', 'N5'], ['connector_complement', 'NC'], ['pin_complement', 'NC'] ])]
		])],
		['27', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: L5'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'L4'], ['connector_complement', '6'], ['pin_complement', '5'] ])]
		])],
		['28', new Map([
			['type', 'FPGA'],
			['connected_to', 'FPGA: J16'],
			['is_diff_pair', 'true'],
			['diff_pair_data', new Map([ ['type', 'DIFF_COMPL'], ['pin_fpga_complement', 'J17'], ['connector_complement', '5'], ['pin_complement', '16'] ])]
		])],
		['29', new Map([
			['type', 'FIXED_GND'],
			['connected_to', 'GND'],
			['is_diff_pair', 'false']
		])],
		['30', new Map([
			['type', 'FIXED_33V'],
			['connected_to', '3.3V'],
			['is_diff_pair', 'false']
		])]
	])]
]);
